backend/models/Attribute.php
<?php
/**
 * 字段模型
 */
namespace backend\models;
use yii\db\ActiveRecord;

class Attribute extends ActiveRecord
{
    public static function tableName()
    {
        return "{{%attribute}}";
    }

    public function rules()
    {
        return [
            ['id','safe'],
            [['name','note','field','type','default_value','remark'],'string'],
            [['model_id','create_time','update_time'],'integer']
        ];
    }

    public function attributeLabels()
    {
        return [
            'name'          => '字段标识',
            'note'          => '字段注释',
            'field'         => '字段定义',
            'type'          => '数据类型',
            'default_value' => '默认值',
            'model_id'      => '模型id',
            'create_time'   => '创建时间',
            'update_time'   => '更新时间',
            'remark'        => '备注'
        ];
    }

    public static function findModel($id)
    {
        if (($model = Attribute::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/controllers/AttributeController.php
<?php
/* author:jj  date:2016/09/21 */
namespace backend\controllers;

use backend\models\Table;
use Yii;
use yii\filters\VerbFilter;
use backend\models\Attribute;
use backend\models\Adminlog;

class AttributeController extends CommonController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * 新增字段
     */
    public function actionCreate($model_id)
    {
        $request = Yii::$app->request;
        $tbPrefix = Yii::$app->params['tablePrefix'];
        $model = new Attribute();
        if($request->isPost){
            $post = $request->post();
            $data = $request->post()['Attribute'];
            $data['create_time'] = $data['update_time'] = time();
            $post['Attribute'] = $data;
            $modelName = Table::findOne($data['model_id']);

            try{
                //1.检查数据表是否存在
                $sql = 'SHOW TABLES LIKE "'.$tbPrefix.$modelName->name.'"';
                $res = Yii::$app->db->createCommand($sql)->execute();

                //如果表不存在则要创建一个新表
                if(!$res){
                    if($data['default_value']!=''){
                        $sql = 'CREATE TABLE '.$tbPrefix.$modelName->name." (
                    {$data['name']} {$data['field']} DEFAULT '{$data['default_value']}' COMMENT '{$data['note']}'
                    )ENGINE='".$modelName->engine_type."'";
                    }else{
                        $sql = 'CREATE TABLE '.$tbPrefix.$modelName->name." (
                    {$data['name']} {$data['field']} COMMENT '{$data['note']}'
                    )ENGINE='".$modelName->engine_type."'";
                    }

                    Yii::$app->db->createCommand($sql)->execute();
                    $model->load($post) && $model->save();
                    Adminlog::saveLog($this->route,"创建了{$modelName->name}数据表并新增了{$data['name']}字段");
                    return $this->redirect(['table/attribute','id'=>$model_id]);

                    //2.为数据表新增字段
                    if($data['default_value']!=''){
                        $sql = 'ALTER TABLE '.$tbPrefix.$modelName->name." ADD {$data['name']} {$data['field']} DEFAULT '{$data['default_value']}' COMMENT '{$data['note']}'";
                    }else{
                        $sql = 'ALTER TABLE '.$tbPrefix.$modelName->name." ADD {$data['name']} {$data['field']} COMMENT '{$data['note']}'";
                    }

                    Yii::$app->db->createCommand($sql)->execute();
                    $model->load($post) && $model->save();
                    Adminlog::saveLog($this->route,"向{$modelName->name}表增加了{$data['name']}字段");
                    return $this->redirect(['table/attribute','id'=>$model_id]);
                }
            }catch(\Exception $e){
                Yii::$app->session->setFlash('msg-attr',['status'=>'danger','mes'=>'新增字段出错!']);
                return $this->redirect(['table/attribute','id'=>$model_id]);
            }

        }else{
            return $this->render('create',[
                'model_id'=>$model_id,
                'model' => $model
            ]);
        }
    }

    /**
     * 编辑字段
     */
    public function actionUpdate($id)
    {
        $request = Yii::$app->request;
        $model = Attribute::findModel($id);
        $tbModel = Table::findOne($model->model_id);

        if($request->isPost){
            $post = $request->post();
            $data = $post['Attribute'];
            $data['update_time'] = time();
            $post['Attribute'] = $data;
            $tbPrefix = Yii::$app->params['tablePrefix'];

            $sql = 'ALTER TABLE '.$tbPrefix.$tbModel->name.' CHANGE '.$model->name.' '.$data['name']." {$data['field']} DEFAULT '{$data['default_value']}' COMMENT '{$data['note']}'";
            try{
                Yii::$app->db->createCommand($sql)->execute();
            }catch(\Exception $e){
                Yii::$app->session->setFlash('msg-attr',['status'=>'danger','mes'=>'修改字段失败!']);
                return $this->redirect(['/table/attribute','id'=>$tbModel->id]);
            }

            $model->load($post) && $model->save();
            Adminlog::saveLog($this->route,"在{$tbModel->name}表中修改了字段");
            return $this->redirect(['/table/attribute','id'=>$tbModel->id]);
        }else{
            return $this->render('edit',[
                'model_id'=>$model->model_id,
                'model' => $model
            ]);
        }
    }

    /**
     * 删除字段
     */
    public function actionDelete($id)
    {
        $model = Attribute::findModel($id);
        $tableModel = Table::findOne($model->model_id);
        $tbPrefix = Yii::$app->params['tablePrefix'];

        $sql = 'ALTER TABLE '.$tbPrefix.$tableModel->name.' DROP COLUMN '.$model->name;
        try{
            Yii::$app->db->createCommand($sql)->execute();
        }catch(\Exception $e){
            Yii::$app->session->setFlash('msg-attr',['status'=>'danger','mes'=>'删除字段失败!']);
            return $this->redirect(['/table/attribute','id'=>$tableModel->id]);
        }
        Adminlog::saveLog($this->route,"在{$tableModel->name}表中删除了字段{$model->name}");
        $model->delete();
        return $this->redirect(['/table/attribute','id'=>$tableModel->id]);
    }


}

backend/views/attribute/_form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\Attribute */
/* @var $form yii\widgets\ActiveForm */

?>

<div class="table-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'id')->textInput(['readonly'=>true]) ?>

    <?= $form->field($model, 'model_id')->textInput(['readonly'=>true,'value'=>$model_id]) ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'note')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'type')->dropDownList(['0'=>'请选择...','string'=>'字符串','integer'=>'数字','float'=>'浮点数','text'=>'文本框'],['id'=>'type']) ?>

    <?= $form->field($model, 'field')->textInput(['maxlength' => true,'id'=>'field']) ?>

    <?= $form->field($model, 'default_value')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'remark')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? '确定' : '修改', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

<script>
    <?php $this->beginBlock('attri') ?>
        $('form').submit(function(e){
            if($('#type').val()=='0'){
                alert('请选择数据类型!');
                e.preventDefault();
                return false;
            }
        });

        $('#type').bind('change',function(){
            var val = $(this).val();
            var field = $('#field');
            switch(val){
                case 'string':
                    var txt = "VARCHAR(255) NOT NULL";
                    field.val(txt);
                    break;

                case 'integer':
                    var txt = "INT(10) NOT NULL";
                    field.val(txt);
                    break;

                case 'float':
                    var txt = "FLOAT NOT NULL";
                    field.val(txt);
                    break;

                case 'text':
                    var txt = "TEXT NOT NULL";
                    field.val(txt);
                    break;
            }
        });
    <?php $this->endBlock(); ?>
</script>
<?php $this->registerJs($this->blocks['attri'],\yii\web\View::POS_LOAD); ?>

backend/views/attribute/attribute.php
<?php
use yii\grid\GridView;
use yii\helpers\Url;
use yii\helpers\Html;

$this->title = $modelName.'模型 字段列表';
?>
<?= Html::a('新增',Url::to(['/attribute/create','model_id'=>$model->id]),['class'=>'btn btn-info']) ?> <br/>

<?php
    $mess = Yii::$app->session->getFlash('msg-attr');
    if($mess){
        $str = '<div class="alert alert-'.$mess['status'].' alert-dismissable">
                            <button type="button" class="close" data-dismiss="alert"
                                    aria-hidden="true">
                                &times;
                            </button>
                            '.$mess['mes'].'
                            </div>';
        echo $str;
    }
?>

<div class="content">

    <?=
        GridView::widget([
            'dataProvider'  => $dataProvider,
            'columns'=>[
                'name',
                'note',
                'type',
                [
                    'attribute'   => 'create_time',
                    'value' => function($data){
                        return date('Y-m-d H:i:s',$data->create_time);
                    }
                ],

                [
                    'class' => 'yii\grid\ActionColumn',
                    'header'=>'操作',
                    'template'=> '{update} {delete}',
                    'buttons'=>[
                        'update'  => function($url,$model,$key){
                            $url = Url::toRoute(['attribute/update','id'=>$model->id]);
                            return Html::a('<i class="fa fa-edit"></i> 编辑',$url,['class'=>'btn btn-info btn-xs']);
                        },

                        'delete'  => function($url,$model,$key){
                            $url = Url::toRoute(['attribute/delete','id'=>$model->id]);
                            return Html::a('<i class="fa fa-trash-o"></i> 删除',$url,['class'=>'btn btn-danger btn-xs','data'=>['confirm'=>'确定要删除这个字段吗?','method'=>'post']]);
                        }
                    ]
                ]
            ],
        ]);
    ?>
</div>

backend/views/attribute/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model backend\models\Attribute */

$this->title = '新增字段';
$this->params['breadcrumbs'][] = ['label' => 'Tables', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="table-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model_id'=>$model_id,
        'model' => $model,
    ]) ?>

</div>

backend/views/attribute/edit.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\Attribute */

$this->title = '编辑字段: ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Tables', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="table-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model_id'=>$model_id,
        'model' => $model,
    ]) ?>

</div>